# Generated by Django 5.2 on 2025-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(help_text='Envie imagens com proporção 4:3 para melhor visualização', upload_to='carousel/', verbose_name='Imagem do Carrossel')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Itens com ordem menor aparecem primeiro', verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Item do Carrossel',
                'verbose_name_plural': 'Itens do Carrossel',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
