# Generated by Django 5.2 on 2025-04-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='menu.tipo'),
        ),
    ]
